name: MEXC Scraper, Translate & Push JSON

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape-and-translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 selenium undetected-chromedriver crewai google-generativeai

      - name: Verify Secrets
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          if [ -z "${GEMINI_API_KEY}" ]; then
            echo "❌ GEMINI_API_KEY secret is missing!"
            exit 1
          fi
          if [ -z "${{ secrets.ACTIONS_PAT }}" ]; then
            echo "❌ ACTIONS_PAT secret is missing!"
            exit 1
          fi
          # Add these secret checks for WordPress
          if [ -z "${{ secrets.WP_USER }}" ]; then
            echo "❌ WP_USER secret is missing!"
            exit 1
          fi
          if [ -z "${{ secrets.WP_APP_PASSWORD }}" ]; then
            echo "❌ WP_APP_PASSWORD secret is missing!"
            exit 1
          fi
          if [ -z "${{ secrets.WP_URL }}" ]; then
            echo "❌ WP_URL secret is missing!"
            exit 1
          fi

      - name: Set PYTHONPATH  # ✅ FIX: Add this step!
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Run MEXC scraping and translation via CrewAI
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          WP_USER: ${{ secrets.WP_USER }}         # Pass WP_USER from GitHub Secrets
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}  # Pass WP_APP_PASSWORD from GitHub Secrets
          WP_URL: ${{ secrets.WP_URL }}           # Pass WP_URL from GitHub Secrets
        run: python main.py

      - name: Commit and push JSON output
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add mexc_translated_articles.json
          git status
          git diff --cached --quiet || git commit -m "Update mexc_translated_articles.json"
          git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git main
